source os_spatial_index : db_slave
{
        sql_query               = select auto_id,\
		i.name1,name2,full_county as county,i.local_type as type,i.country, replace(island_name,'_',' ') as island_name,i.region, i.geometry_x,i.geometry_y,i.images, gridref\
		from os_spatial_index i inner join os_open_places using (id) 

	sql_field_string	= name1
	sql_field_string	= name2
	sql_field_string	= county
        sql_attr_string         = local_type
	sql_field_string	= country
	sql_field_string	= island_name
	sql_attr_string		= region

        sql_attr_uint           = geometry_x
        sql_attr_uint           = geometry_y
        sql_attr_uint           = images
	sql_field_string	= gridref
}

source iom_spatial_index : db_slave
{
        sql_query               = select seq+2000000 as auto_id,
                i.name1,'' as name2,region as county,IF(BINARY def_nam = UPPER(def_nam), 'Town', '') as type,i.country, i.island_name,i.region, 
		i.geometry_x,i.geometry_y,i.images, gridref
                from os_spatial_index i inner join os_gaz_250 o on (id = CONCAT('IOM-',seq)) where o.full_county = 'Isle of Man' and i.country = 'Isle of Man'

        sql_field_string        = name1
        sql_field_string        = name2
        sql_field_string        = county
        sql_attr_string         = local_type
        sql_field_string        = country
        sql_field_string        = island_name
        sql_attr_string         = region

        sql_attr_uint           = geometry_x
        sql_attr_uint           = geometry_y
        sql_attr_uint           = images
        sql_field_string        = gridref
}

source ie_spatial_index : db_slave
{
        sql_query               = select id+1000000 as auto_id,\
		name1,name2,i.county,i.town_class as type,i.country, island_name,i.county as region, e as geometry_x,n as geometry_y, i.images,grid_reference as gridref\
		from ie_spatial_index i inner join ie_open_places using (id)

	sql_field_string	= name1
	sql_field_string	= name2
	sql_field_string	= county
        sql_attr_string         = local_type
	sql_field_string	= country
	sql_field_string	= island_name
	sql_attr_string		= region

        sql_attr_uint           = geometry_x
        sql_attr_uint           = geometry_y
        sql_attr_uint           = images
	sql_field_string	= gridref
}

index spatial_index
{
        source                  = os_spatial_index
        source                  = iom_spatial_index
        source                  = ie_spatial_index
        path                    = /var/lib/manticore/data/spatial_index
        min_word_len            = 1

        expand_keywords		= 1
        min_prefix_len          = 2
        dict			= crc
        prefix_fields           = name1,name2,county,gridref
}

