#!/bin/sh

cd /var/geogridfs/

echo apache2ctl graceful-stop
apache2ctl graceful-stop

sleep 1

while ps aux | grep apache | grep -v grep; do
        echo "apache still running, sleeping again"
        sleep 2
done

echo ./off
sudo -u www-data ./off

echo ./on
sudo -u www-data ./on

echo ./remount
php remount

echo ls -l /var/www/geograph_live/public_html/geophotos
ls -l /var/www/geograph_live/public_html/geophotos

echo "ps aux | grep python"
ps aux | grep python | grep -v grep

echo 

if [ $1 = "run" ]; then
        echo "apache2ctl start";
        apache2ctl start
else
        echo "apache2ctl start #(NOT run)"
fi

