--- #YAML:1.0
name:                WebService-Geograph-API
version:             0.04
abstract:            Perl interface to the Geograph.co.uk API
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    Date::Simple:                  3.02
    HTTP::Request:                 1.4
    HTTP::Response:                1.53
    LWP::UserAgent:                2.033
    Test::Simple:                  0.44
    URI:                           1.35
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Spiros Denaxas (s [dot] denaxas [@] gmail [dot]com)
