/*
 * Compass.java
 *
 * Created on 23 June 2007, 10:19
 */

package net.brassedoff;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JComponent;

/**
 *
 * @author  david
 */
public class Compass extends JComponent {
    
    int bearing = 0;
    int prevX = 0;
    int prevY = 0;
    int newX = 0;
    int newY = 0;
    
    /** Creates new form Compass */
    public Compass() {
        initComponents();
        
        addMouseListener(new MouseAdapter() {
            public void mousePressed(MouseEvent me) {
                track(me);
            }
        });
        
    }
    
    private void track(MouseEvent me) {
        
        System.out.println("Mouse at " + me.getX() + ", " + me.getY());
        newX = me.getX();
        newY = me.getY();
        repaint();
        
    }

    
    public void paintComponent(Graphics g) {
        
        // we need to draw a circle in the middle of the compass area
        
        g.setColor(Color.WHITE);
        g.fillOval(0, 0, 49, 49);
        g.setColor(Color.BLACK);
        g.drawLine(25, 25, newX, newY);
        
        
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());

        setMaximumSize(new java.awt.Dimension(50, 50));
        setMinimumSize(new java.awt.Dimension(50, 50));
        setPreferredSize(new java.awt.Dimension(50, 50));
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
