<?php

// It's assumed that the autoloader or relevant includes will handle these paths.
// If running standalone, these paths might need adjustment.
require_once __DIR__ . '/../libs/geograph/user.class.php';
require_once __DIR__ . '/../libs/adodb/adodb.inc.php'; // Required by user.class.php

// --- Mocking GeographDatabaseConnection ---
// This is a very basic mock to prevent fatal errors.
// In a real test suite, this would be more sophisticated (e.g., using PHPUnit mocks or a dedicated test database).
if (!function_exists('GeographDatabaseConnection')) {
    function GeographDatabaseConnection($allow_readonly = false) {
        // Return a mock ADODB object or a stdClass with expected methods if necessary
        $mockDB = new stdClass();
        $mockDB->readonly = $allow_readonly;
        $mockDB->Quote = function($value) {
            // Simple quote for testing purposes
            return "'" . addslashes($value) . "'";
        };
        $mockDB->GetRow = function($sql) {
            // Simulate fetching a user row.
            // This would need to be more dynamic for comprehensive tests.
            if (strpos($sql, "select * from user where user_id=1") !== false) {
                return array(
                    'user_id' => 1,
                    'realname' => 'Test User',
                    'nickname' => 'tester',
                    'email' => 'test@example.com',
                    'rights' => 'basic',
                    'displayclass' => 'thumbs', // Simulate a user with a saved preference
                    'upload_size' => 1024
                );
            }
            if (strpos($sql, "select * from user where user_id=2") !== false) {
                 return array(
                    'user_id' => 2,
                    'realname' => 'Default User',
                    'nickname' => 'defaulttester',
                    'email' => 'default@example.com',
                    'rights' => 'basic',
                    // No displayclass set here to test default
                    'upload_size' => 1024
                );
            }
            if (strpos($sql, "select * from user where nickname = 'tester_nick'") !== false) {
                 return array(
                    'user_id' => 3,
                    'realname' => 'Nickname User',
                    'nickname' => 'tester_nick',
                    'email' => 'nick@example.com',
                    'rights' => 'basic',
                    'displayclass' => 'grid', // Simulate a user with a saved preference
                    'upload_size' => 1024
                );
            }
            if (strpos($sql, "select * from user where nickname = 'default_tester_nick'") !== false) {
                 return array(
                    'user_id' => 4,
                    'realname' => 'Default Nickname User',
                    'nickname' => 'default_tester_nick',
                    'email' => 'default_nick@example.com',
                    'rights' => 'basic',
                    // No displayclass set here
                    'upload_size' => 1024
                );
            }
            return array(); // Default empty response
        };
        $mockDB->Execute = function($sql) {
            // Simulate successful execution
            // For `updateProfile` tests, we're more interested in the object state change.
            // A real test would check if the SQL generated by updateProfile is correct.
            echo "Mock DB Execute: " . $sql . "\n"; // For debugging test execution
            return true;
        };
        $mockDB->Insert_ID = function() {
            return 123; // Dummy insert ID
        };
        // Add any other methods called by GeographUser that need mocking
        return $mockDB;
    }
}

// --- Test Functions ---

function testUpdateProfileSetsDisplayClass() {
    echo "Running testUpdateProfileSetsDisplayClass...\n";
    $user = new GeographUser(); // Create a guest user or load a mock user
    $user->user_id = 1; // Simulate a logged-in user
    $user->registered = true;
    // Mock existing properties that updateProfile might need
    $user->realname = "Initial Name";
    $user->nickname = "initialnick";
    $user->email = "initial@example.com";
    $user->website = "";
    $user->public_email = 0;
    $user->search_results = 15;
    $user->slideshow_delay = 5;
    $user->about_yourself = "";
    $user->public_about = 1;
    $user->age_group = 0;
    $user->use_age_group = 0;
    $user->home_gridsquare = null;
    $user->ticket_public = 'everyone';
    $user->ticket_option = 'all';
    $user->message_sig = "";
    $user->expand_about = 0;
    $user->upload_size = 1024;
    $user->submission_method = "submit2";
    $user->submission_new = "1";
    $user->gravatar = "unknown";
    $user->salt = "somesalt";
    $user->password = "somepassword";
    $user->displayclass = "full"; // Initial value


    $profileData = array(
        'realname' => $user->realname,
        'nickname' => $user->nickname,
        'website' => $user->website,
        'email' => $user->email, // Email change is a separate flow, keep it same for this test
        'public_email' => $user->public_email,
        'search_results' => $user->search_results,
        'slideshow_delay' => $user->slideshow_delay,
        'about_yourself' => $user->about_yourself,
        'public_about' => $user->public_about,
        'age_group' => $user->age_group,
        'use_age_group' => $user->use_age_group,
        'grid_reference' => '', // Assuming home_gridsquare logic is handled separately
        'ticket_public' => $user->ticket_public,
        'ticket_option' => $user->ticket_option,
        'message_sig' => $user->message_sig,
        'expand_about' => $user->expand_about,
        'upload_size' => $user->upload_size,
        'submission_method' => $user->submission_method,
        'submission_new' => $user->submission_new,
        'gravatar_reset' => null,
        'oldpassword' => '', // Not testing password change here
        'password1' => '',
        'password2' => '',
        'displayclass' => 'thumbs' // The preference to test
    );
    $errors = array();

    // NOTE: Direct database save verification is limited by the mock DB.
    // We are primarily testing if the object's property is updated.
    $user->updateProfile($profileData, $errors);

    if ($user->displayclass === 'thumbs') {
        echo "SUCCESS: updateProfile correctly updated displayclass property to 'thumbs'.\n";
    } else {
        echo "FAILURE: updateProfile did not update displayclass property. Expected 'thumbs', got '{$user->displayclass}'.\n";
    }
    if (!empty($errors)) {
        echo "INFO: updateProfile reported errors: " . print_r($errors, true) . "\n";
    }
}

function testUserLoadsWithPreference() {
    echo "Running testUserLoadsWithPreference...\n";
    // GeographUser constructor with UID 1 should get 'thumbs' from our mock DB
    $user = new GeographUser(1);
    if ($user->user_id == 1 && $user->displayclass === 'thumbs') {
        echo "SUCCESS: GeographUser(1) loaded with displayclass 'thumbs'.\n";
    } else {
        echo "FAILURE: GeographUser(1) did not load displayclass 'thumbs'. Got '{$user->displayclass}'. User ID: {$user->user_id}\n";
    }
}

function testUserLoadsWithDefaultPreference() {
    echo "Running testUserLoadsWithDefaultPreference...\n";
    // GeographUser constructor with UID 2 should default to 'full' as per mock DB
    $user = new GeographUser(2);
     if ($user->user_id == 2 && $user->displayclass === 'full') {
        echo "SUCCESS: GeographUser(2) defaulted to displayclass 'full'.\n";
    } else {
        echo "FAILURE: GeographUser(2) did not default to 'full'. Got '{$user->displayclass}'. User ID: {$user->user_id}\n";
    }
}

function testLoadByNicknameWithPreference() {
    echo "Running testLoadByNicknameWithPreference...\n";
    $user = new GeographUser();
    $user->loadByNickname('tester_nick'); // Should get 'grid' from mock DB
    if ($user->user_id == 3 && $user->displayclass === 'grid') {
        echo "SUCCESS: loadByNickname('tester_nick') loaded with displayclass 'grid'.\n";
    } else {
        echo "FAILURE: loadByNickname('tester_nick') did not load displayclass 'grid'. Got '{$user->displayclass}'. User ID: {$user->user_id}\n";
    }
}

function testLoadByNicknameWithDefaultPreference() {
    echo "Running testLoadByNicknameWithDefaultPreference...\n";
    $user = new GeographUser();
    $user->loadByNickname('default_tester_nick'); // Should default to 'full'
    if ($user->user_id == 4 && $user->displayclass === 'full') {
        echo "SUCCESS: loadByNickname('default_tester_nick') defaulted to displayclass 'full'.\n";
    } else {
        echo "FAILURE: loadByNickname('default_tester_nick') did not default to 'full'. Got '{$user->displayclass}'. User ID: {$user->user_id}\n";
    }
}

function testNewUserDefaultsDisplayClass() {
    echo "Running testNewUserDefaultsDisplayClass...\n";
    // A new user object (uid=0) shouldn't hit the DB for these properties initially
    // but the property should exist and ideally have a default if accessed,
    // though user.class.php seems to set it during load from DB.
    // Let's check the state if no DB load happens.
    $user = new GeographUser(0); // Guest user
    if (!isset($user->displayclass) || $user->displayclass === null || $user->displayclass === 'full' || $user->displayclass === '') {
        // In the current implementation, it seems $this->displayclass is only populated
        // from the DB record or when updateProfile is called. A guest user (uid=0)
        // doesn't have a displayclass property explicitly set to 'full' by default in the constructor
        // unless it's loaded from DB (which uid=0 won't).
        // The default 'full' is more strongly enforced in search.php or upon actual user load.
        // For a truly new user object not loaded, its state is less defined for this prop.
        // However, the critical part is it defaults to 'full' if *loaded* and not set.
        echo "SUCCESS/INFO: New GeographUser(0) displayclass is not strictly 'full' by default in constructor but will be handled by loading logic or search.php defaults. Current state: '{$user->displayclass}'. This is acceptable as defaults apply on load.\n";
    } else {
        echo "FAILURE: New GeographUser(0) has an unexpected displayclass. Expected unset, null, or 'full', got '{$user->displayclass}'.\n";
    }
}


// --- Run Tests ---
echo "--- Starting User Preference Tests (user.class.php) ---\n";
testUpdateProfileSetsDisplayClass();
echo "\n";
testUserLoadsWithPreference();
echo "\n";
testUserLoadsWithDefaultPreference();
echo "\n";
testLoadByNicknameWithPreference();
echo "\n";
testLoadByNicknameWithDefaultPreference();
echo "\n";
testNewUserDefaultsDisplayClass();
echo "--- Finished User Preference Tests ---\n\n";

?>
