#!/bin/bash
set -eu -o pipefail

## the wrapper, now has all the logic, to create all indexes!
# the old init script just called indexer directly, but it didnt build the indexes in the right order. The wrapper now takes care of that!

/usr/local/bin/indexer-wrapper.php

# vim: ai ts=2 sw=2 et sts=2 ft=sh
