{assign var="page_title" value="Routes in Pictures :: Explore"}
{include file="_std_begin.tpl"}
<script src="{"/sorttable.js"|revision}"></script>

<h2>Routes in Pictures</h2>

{if $filter}
    <form method="get" action="{$script_name}">
    <p>{if $references}In <select name="ri">
    	{html_options options=$references selected=$ri}
    </select>{/if}
    {if $i}
    	<input type="checkbox" name="i" value="{$i}" checked="checked" 
    	id="i"/><label for="i">Limited to <a href="/search.php?i={$i}">Search</a></label>
    {/if}
    {foreach from=$extra key=name item=value}
    	<input type="hidden" name="{$name}" value="{$value}"/>
    {/foreach}
    <input type="submit" value="Go"/></p></form>
 {/if}  

	<p style="font-size:0.8em">The routes accessible from this page simply show the first geograph in the same 1km gridsquares that the route passes through. In many cases the image won't be approriate for the route, or indeed very close to the actual route (but in all cases should be within about 1.4km)*.</p>
	
{foreach from=$tables item=table}

	<h3>{$table.title}</h3>
	{if $table.total > 0}
	
		<table class="report sortable" id="reportlist" border="1" bordercolor="#dddddd" cellspacing="0" cellpadding="5">
		<thead><tr>
			<td>Route</td>
			<td>Gridsquares</td>
			<td>Order</td>
			<td>Links</td>
		</tr></thead>
		<tbody>

		{foreach from=$table.table item=row}
		<tr>
			<td><a href="/search.php?route_id={$row.route_id}{if $row.orderby}&amp;orderby={$row.orderby}{/if}&amp;do=1">{$row.name}</a></td>
			<td align="right" sortvalue="{$row.count}">{$row.count|thousends} <small style="color:gray">[{$row.myriads}]</small></td>
			<td>{$row.order}</td>
			<td style="font-size:0.6em;">
				<a href="/search.php?route_id={$row.route_id}{if $row.orderby}&amp;orderby={$row.orderby}{/if}&amp;displayclass=thumbs&amp;do=1">Thumbs&nbsp;Only</a>
				<a href="/search.php?route_id={$row.route_id}{if $row.orderby}&amp;orderby={$row.orderby}{/if}&amp;displayclass=slide&amp;do=1">Slide&nbsp;Show</a>
				<a href="/search.php?route_id={$row.route_id}{if $row.orderby}&amp;orderby={$row.orderby}&amp;reverse_order_ind=1{/if}&amp;do=1">Reverse&nbsp;Order</a>
			</td>
		</tr>
		{/foreach}

		</tbody>
		</table>

	{else}
		<p><i>No Results to Display</i></p>
	{/if}
{/foreach}

{if $footnote}
	{$footnote}
{/if}

<p style="background-color:#dddddd;padding:10px">For more information on National Trails see {external href="http://www.nationaltrail.co.uk/" text="nationaltrail.co.uk"}, <br/>and for details of Cycle Routes see {external href="http://www.systrans.org.uk/" text="sustrans.org.uk"}.</p>

<p>*Searches generated by this page only return first geographs, so prevent highly saturated squares taking over the search, in the future hope to 'choose' the best picture based on the relevence to the route.</p>

<div class="copyright">Where applicable routes featured on this page, Based upon Landranger&reg; 1:50 000 scale map with the permission of Ordnance Survey on behalf of The Controller of Her Majesty's Stationery Office, &copy; Crown copyright Ordnance Survey&reg. All Rights Reserved. Educational licence 100045616. National Cycle Routes reproduced with permission of Sustrans Ltd, &copy; copyright 2006.</div>


{include file="_std_end.tpl"}
