#!/usr/bin/perl

my $path="/var/www/geograph_live/backups";



my ($sec,$min,$hour,$day, $month, $year) = (localtime)[0,1,2,3,4,5];
$month++;
$year+=1900;

#now backup database
my $file=sprintf("geograph_db_%04d-%02d-%02d_%02d%02d.mysql.gz", $year, $month, $day, $hour, $min, $sec);
my $outfile="$path/$file";

print "Backing up live database, please wait...\n";


# we ignore the exif tables, as they are huge in comparison the rest
# gridimage search and kml are just derived data that can be rebuilt

$cmd="/usr/local/mysql/bin/mysqldump --no-defaults --opt ".
	"--ignore-table=geograph_live.gridimage_search ".
	"--ignore-table=geograph_live.gridimage_kml ".
	"--ignore-table=geograph_live.gridimage_exif1 ".
	"--ignore-table=geograph_live.gridimage_exif ".
	"-ugeograph -pm4pp3r geograph_live | gzip > $outfile";
`$cmd`;

my $size=(stat($outfile))[7];
print "Completed. $outfile ($size bytes)\n\n";




#now clean out old backups

print "Deleting old backups...\n";
my $age=14;


opendir(DIR, $path) or die "can't opendir $path: $!";
while (defined(my $file = readdir(DIR))) 
{
	my $full=$path."/".$file;
	if (-f $full && -M $full > $age)
	{
		unlink($full);
                print "    deleting $full\n";
	}
	

}
closedir(DIR);	



print "Completed!\n";



