#!/bin/bash
#find /var/www/geograph_live/public_html/templates/basic/cache -mtime +2 | xargs rm

cd /var/www/geograph_live/public_html/templates/basic/cache

mkdir _attic

mv search/ _attic/
mv img*/ _attic/

nice rm -Rf _attic

nice find . -mtime +2 -print0 | xargs -n500 -0 rm -f

nice find -depth -type d -empty | xargs rmdir

