#!/usr/bin/perl

my $path="/var/www/geograph_live/backups";



my ($sec,$min,$hour,$day, $month, $year) = (localtime)[0,1,2,3,4,5];
$month++;
$year+=1900;

#now backup database
my $file=sprintf("geograph_db_%04d-%02d-%02d_%02d%02d.mysql.gz", $year, $month, $day, $hour, $min, $sec);
my $outfile="$path/$file";

print "Backing up live database, please wait...\n";


$cmd="/usr/bin/mysqldump --no-defaults --opt ".

##SEE: http://www.geograph.org.uk/admin/tables.php

#derived tables - will be rebuilt
	"--ignore-table=geograph_live.gridimage_search ".
	"--ignore-table=geograph_live.gridimage_kml ".
        "--ignore-table=geograph_live.user_gridsquare ".
        "--ignore-table=geograph_live.user_stat ".
        "--ignore-table=geograph_live.user_quadsquare ".
        "--ignore-table=geograph_live.vote_stat ".
        "--ignore-table=geograph_live.game_image_rate ".
        "--ignore-table=geograph_live.gridimage_group_stat ".
        "--ignore-table=geograph_live.gridsquare_log ".
        "--ignore-table=geograph_live.gridimage_size ".
        "--ignore-table=geograph_live.gridimage_exif_size ".

#archive tables (not certain we do want to exclude these?)
#        "--ignore-table=geograph_live.gridimage_ticket_archive ".  
#        "--ignore-table=geograph_live.queries_archive ".

#virtual tables (union=gridimage_ticket,gridimage_ticket_archive_
        "--ignore-table=geograph_live.gridimage_ticket_merge ".

#large tables - not worth backing up
	"--ignore-table=geograph_live.gridimage_exif ".
	"--ignore-table=geograph_live.gridimage_exif1 ".
        "--ignore-table=geograph_live.gridimage_exif2 ".
        "--ignore-table=geograph_live.photo_log ".
        "--ignore-table=geograph_live.gridimage_diversity ".
        "--ignore-table=geograph_live.geocubes ".
        "--ignore-table=geograph_live.event_log ".
        "--ignore-table=geograph_live.gridimage_group ".
        "--ignore-table=geograph_live.gridimage_scale ".

#various imported tables
        "--ignore-table=geograph_live.scenic_votes ".
        "--ignore-table=geograph_live.gridimage_groupby ".
        "--ignore-table=geograph_live.gridimage_search_extract ".

#static tables  - not worth backing up EVERY DAY
        "--ignore-table=geograph_live.os_gaz ".
        "--ignore-table=geograph_live.os_gaz_new ".
        "--ignore-table=geograph_live.os_gaz_old ".
        "--ignore-table=geograph_live.placename_index ".
        "--ignore-table=geograph_live.loc_placenames ".
        "--ignore-table=geograph_live.loc_abgaz ".
        "--ignore-table=geograph_live.loc_wikipedia ".
        "--ignore-table=geograph_live.loc_ppl ".
        "--ignore-table=geograph_live.loc_towns ".
        "--ignore-table=geograph_live.postcode_codeopen ".

#various tmp tables - some are big!
        "--ignore-table=geograph_live.aagaz ".
        "--ignore-table=geograph_live.cent1 ".
        "--ignore-table=geograph_live.gridimage2 ".
        "--ignore-table=geograph_live.gridsquare2 ".
        "--ignore-table=geograph_live.gridimage_land ".
        "--ignore-table=geograph_live.tmp_percentage ".
        "--ignore-table=geograph_live.tmplook ".
        "--ignore-table=geograph_live.tmppost ".
        "--ignore-table=geograph_live.tmp_post_times ".
        "--ignore-table=geograph_live.user2 ".
        "--ignore-table=geograph_live.user_dev ".
        "--ignore-table=geograph_live.devuser ".
        "--ignore-table=geograph_live.gridsquare_land ".
        "--ignore-table=geograph_live.gridimage_group_old ".
        "--ignore-table=geograph_live.gridimage_exif_size ".
        "--ignore-table=geograph_live.gridimage_map ".
        "--ignore-table=geograph_live.mapcacheold1 ".
        "--ignore-table=geograph_live.mapcache3 ".
        "--ignore-table=geograph_live.mapcache2old4 ".
        "--ignore-table=geograph_live.mapcache2old3 ".
        "--ignore-table=geograph_live.mapcache2old2 ".
        "--ignore-table=geograph_live.mapcache2old ".

	##bunch more tables
        "--ignore-table=geograph_live._gridimage_ticket ".
        "--ignore-table=geograph_live._gridimage_ticket_comment ".

        "--ignore-table=geograph_live.category_stat_tmp_years ".

        "--ignore-table=geograph_live.event ".
        "--ignore-table=geograph_live.event_handled_by ".

        "--ignore-table=geograph_live.explorermaps ".
        "--ignore-table=geograph_live.exploreroutlines1 ".

        "--ignore-table=geograph_live.ftf_test ".
        "--ignore-table=geograph_live.ftf_test2 ".

        "--ignore-table=geograph_live.for_tpoints ".

        "--ignore-table=geograph_live.os_gaz_250 ".

        "--ignore-table=geograph_live.gridimage_exif3 ".
        "--ignore-table=geograph_live.gridimage_export ".
        "--ignore-table=geograph_live.tmp_images ".
        "--ignore-table=geograph_live.tmp_description_test4 ".
        "--ignore-table=geograph_live.gridimage_log_2010_03_18 ".

        "--ignore-table=geograph_live.moderation_log_archive ".

        "--ignore-table=geograph_live.os_gaz_250 ".
        "--ignore-table=geograph_live.recent_only ".
        "--ignore-table=geograph_live.hectad_stat_tmp ".
        "--ignore-table=geograph_live.gridimage_export10_titles ".
        "--ignore-table=geograph_live.gridimage_export10 ".
        "--ignore-table=geograph_live.tmp_images_with_tickets ".
        "--ignore-table=geograph_live.tmp_description_test2 ".

        "--ignore-table=geograph_live.tmp_quad1 ".



	"-ugeograph -h192.168.77.36 -pm4pp3r geograph_live | gzip > $outfile";
`$cmd`;

my $size=(stat($outfile))[7];
print "Completed. $outfile ($size bytes)\n\n";




#now clean out old backups

print "Deleting old backups...\n";
my $age=14;


opendir(DIR, $path) or die "can't opendir $path: $!";
while (defined(my $file = readdir(DIR))) 
{
	my $full=$path."/".$file;
	if (-f $full && -M $full > $age)
	{
		unlink($full);
                print "    deleting $full\n";
	}
	

}
closedir(DIR);	



print "Completed!\n";



